export default {
  key: "legal",
  label: "Legal Services",
  description: "Law firms, solo practitioners, and legal service providers.",
  onboarding: {
    websitePlaceholder: "smithlawfirm.com",
    extraContextLabel: "Practice areas or specialties",
    extraContextPlaceholder: "Describe your practice areas, notable cases, or target clients...",
    helperText: "We'll extract your practice areas, attorney profiles, and case results.",
  },
  extraction: {
    hints: "Focus on practice areas (family law, personal injury, business law, etc.), attorney bios and credentials, case results, client testimonials, legal FAQs, and community involvement.",
    priorityDataTypes: ["CUSTOM", "TESTIMONIAL", "FAQ", "TEAM_SPOTLIGHT"],
  },
  content: {
    starterBlueprintSlugs: ["legal-tip", "case-result", "attorney-spotlight"],
    starterChannels: ["LINKEDIN", "FACEBOOK", "INSTAGRAM"],
    starterAngles: [
      "Share a practical legal tip that educates your audience about their rights or common mistakes.",
      "Highlight a case result or settlement that demonstrates your firm's expertise (no confidential details).",
      "Spotlight an attorney on your team — share their background, passion, and what drives them.",
    ],
  },
  integrations: {
    supportedCapabilities: ["case_management", "crm"],
    recommendedProviders: ["clio", "lawmatics"],
    starterAutomations: ["weekly_legal_tip", "new_blog_post_share"],
  },
  terminology: {
    item: "service",
    items: "services",
    customer: "client",
    customers: "clients",
    service: "practice area",
    services: "practice areas",
    offer: "consultation",
    offers: "consultations",
    contentUnit: "legal post",
    contentUnits: "legal posts",
    campaign: "campaign",
    campaigns: "campaigns",
    primaryAction: "advise",
  },
  onboardingSteps: {
    explore: "Reviewing your services...",
    understand: "Understanding your practice areas...",
    insights: "Discovering client needs...",
    prepare: "Preparing your workspace...",
    generate: "Creating legal content...",
  },
  businessDataLabels: {
    itemSingular: "Service",
    itemPlural: "Services",
    launchLabel: "Featured Service",
    categoryLabel: "Practice Area",
    collectionLabel: "Service Collection",
    serviceLabel: "Practice Area",
    offerLabel: "Consultation Offer",
  },
  contentTypeLabels: [
    { key: "client_education", label: "Client Education" },
    { key: "legal_tip", label: "Legal Tip" },
    { key: "common_mistake", label: "Common Mistake" },
  ],
  recommendationTemplates: [
    { type: "case_result", tier: "core", title: "Highlight a Case Result", description: "Showcase a successful outcome to build credibility.", priority: "high", guidance: "Create a post highlighting a successful case result or settlement. Demonstrate expertise without revealing confidential client details.", conditions: { hasData: true } },
    { type: "legal_update", tier: "core", title: "Share a Legal Update", description: "Discuss a recent law change that affects your audience.", priority: "high", guidance: "Create a post about a recent legal change or court decision. Explain what changed, who it affects, and what people should do about it.", conditions: {} },
    { type: "consultation_cta", tier: "core", title: "Encourage Free Consultations", description: "Drive leads to book a consultation.", priority: "high", guidance: "Create a consultation call-to-action post. Explain what a free consultation includes, what to expect, and make it easy to book.", conditions: {} },
    { type: "legal_tip", tier: "secondary", title: "Share a Legal Tip", description: "Educate your audience on a common legal issue.", priority: "medium", guidance: "Share a practical legal tip that helps people understand their rights or avoid a common mistake. Keep it accessible and jargon-free.", conditions: {} },
    { type: "practice_area_spotlight", tier: "secondary", title: "Spotlight a Practice Area", description: "Explain a specific legal service you offer.", priority: "medium", guidance: "Create a practice area spotlight post. Explain what the area covers, who needs it, and how your firm approaches it differently.", conditions: {} },
    { type: "client_testimonial", tier: "secondary", title: "Share a Client Testimonial", description: "Build trust with a real client review.", priority: "medium", guidance: "Feature a client testimonial or review. Share their experience working with the firm and the outcome they achieved.", conditions: { hasData: true } },
    { type: "faq_post", tier: "advanced", title: "Answer a Common Question", description: "Address a frequently asked legal question.", priority: "low", guidance: "Answer a commonly asked legal question in plain language. Be helpful and authoritative — position the firm as the go-to resource.", conditions: {} },
  ],
  ui: { icon: "Scale" },
  techStack: [],
};
