export default {
  key: "real_estate",
  label: "Real Estate",
  description: "Residential and commercial real estate agents, brokers, and teams.",
  onboarding: {
    websitePlaceholder: "smithrealty.com",
    extraContextLabel: "Property or market details",
    extraContextPlaceholder: "Describe your market area, specialties, or paste listing details...",
    helperText: "We'll extract your listings, testimonials, and market expertise.",
  },
  extraction: {
    hints: "Focus on property listings (address, price, bedrooms, sqft), agent bios, testimonials, market stats, neighborhoods, and open house events.",
    priorityDataTypes: ["CUSTOM", "TESTIMONIAL", "STATISTIC", "EVENT"],
  },
  content: {
    starterBlueprintSlugs: ["just-listed", "market-update", "client-success-story"],
    starterChannels: ["INSTAGRAM", "FACEBOOK", "LINKEDIN"],
    starterAngles: [
      "Create a 'just listed' post highlighting a property's best features. Use specific details.",
      "Write a local market insight post sharing a surprising housing stat or trend.",
      "Share a client success story — how the agent helped a buyer or seller achieve their goal.",
    ],
  },
  integrations: {
    supportedCapabilities: ["listing_feed", "crm"],
    recommendedProviders: ["mls_idx", "follow_up_boss"],
    starterAutomations: ["new_listing_post", "open_house_post"],
  },
  terminology: {
    item: "listing",
    items: "listings",
    customer: "buyer",
    customers: "buyers",
    service: "service",
    services: "services",
    offer: "listing",
    offers: "listings",
    contentUnit: "listing post",
    contentUnits: "listing posts",
    campaign: "campaign",
    campaigns: "campaigns",
    primaryAction: "list",
  },
  onboardingSteps: {
    explore: "Exploring your listings...",
    understand: "Understanding your market...",
    insights: "Discovering local opportunities...",
    prepare: "Preparing your workspace...",
    generate: "Creating listing posts...",
  },
  businessDataLabels: {
    itemSingular: "Listing",
    itemPlural: "Listings",
    launchLabel: "New Listing",
    categoryLabel: "Property Type",
    collectionLabel: "Listing Collection",
    serviceLabel: "Service",
    offerLabel: "Promotion",
  },
  contentTypeLabels: [
    { key: "just_listed", label: "Just Listed" },
    { key: "market_insight", label: "Market Insight" },
    { key: "open_house", label: "Open House" },
  ],
  ui: { icon: "Home" },
  techStack: [
    {
      providerKey: "mls_idx",
      label: "MLS / IDX",
      category: "data_source",
      priority: "core",
      status: "planned",
      description: "Import your listings and property details automatically.",
      capabilities: ["imports", "content_source", "data_enrichment", "workflow_trigger"],
    },
    {
      providerKey: "real_estate_crm",
      label: "Real Estate CRM",
      category: "crm",
      priority: "core",
      status: "planned",
      description: "Sync leads, contacts, and follow-up activity from your CRM.",
      capabilities: ["lead_sync", "client_sync", "content_source", "workflow_trigger"],
    },
    {
      providerKey: "facebook_page",
      label: "Facebook Page",
      category: "publishing",
      priority: "core",
      status: "planned",
      description: "Publish and schedule content to your Facebook business page.",
      capabilities: ["publishing", "analytics_source", "scheduling_target"],
    },
    {
      providerKey: "instagram_business",
      label: "Instagram Business",
      category: "publishing",
      priority: "core",
      status: "planned",
      description: "Publish and schedule visual real estate content to Instagram.",
      capabilities: ["publishing", "analytics_source", "scheduling_target"],
    },
    {
      providerKey: "google_business_profile",
      label: "Google Business Profile",
      category: "publishing",
      priority: "recommended",
      status: "planned",
      description: "Share updates and strengthen your local business presence on Google.",
      capabilities: ["publishing", "analytics_source"],
    },
    {
      providerKey: "transaction_management",
      label: "Transaction Management",
      category: "operations",
      priority: "recommended",
      status: "planned",
      description: "Use transaction milestones and workflow data to power smarter automation.",
      capabilities: ["document_source", "workflow_trigger", "client_sync"],
    },
    {
      providerKey: "esignature",
      label: "E-Signature",
      category: "documents",
      priority: "recommended",
      status: "planned",
      description: "Use signed document activity to support workflow automation.",
      capabilities: ["document_source", "workflow_trigger"],
    },
    {
      providerKey: "showing_scheduler",
      label: "Showing Scheduler",
      category: "operations",
      priority: "optional",
      status: "planned",
      description: "Use showing activity and appointments to support event-driven marketing.",
      capabilities: ["workflow_trigger", "client_sync"],
    },
    {
      providerKey: "idx_website",
      label: "Website / IDX Website",
      category: "website",
      priority: "core",
      status: "planned",
      description: "Import website and listing content to improve business context and content generation.",
      capabilities: ["imports", "content_source", "lead_sync", "analytics_source"],
    },
    {
      providerKey: "open_house_lead_capture",
      label: "Open House Lead Capture",
      category: "operations",
      priority: "optional",
      status: "planned",
      description: "Capture and use open house visitor leads for follow-up and event-based campaigns.",
      capabilities: ["lead_sync", "workflow_trigger"],
    },
  ],
};
