export default {
  key: "real_estate",
  label: "Real Estate",
  description: "Residential and commercial real estate agents, brokers, and teams.",
  onboarding: {
    websitePlaceholder: "smithrealty.com",
    extraContextLabel: "Property or market details",
    extraContextPlaceholder: "Describe your market area, specialties, or paste listing details...",
    helperText: "We'll use your website to learn your brand, services, and market expertise.",
  },
  extraction: {
    hints: "Focus on property listings (address, price, bedrooms, sqft), agent bios, testimonials, market stats, neighborhoods, and open house events.",
    priorityDataTypes: ["CUSTOM", "TESTIMONIAL", "STATISTIC", "EVENT"],
  },
  content: {
    starterBlueprintSlugs: ["just-listed", "market-update", "client-success-story"],
    starterChannels: ["INSTAGRAM", "FACEBOOK", "LINKEDIN"],
    starterAngles: [
      "Create a 'just listed' post highlighting a property's best features. Use specific details.",
      "Write a local market insight post sharing a surprising housing stat or trend.",
      "Share a client success story — how the agent helped a buyer or seller achieve their goal.",
    ],
  },
  terminology: {
    item: "property",
    items: "properties",
    customer: "buyer",
    customers: "buyers",
    service: "service",
    services: "services",
    offer: "listing",
    offers: "listings",
    contentUnit: "campaign",
    contentUnits: "campaigns",
    campaign: "campaign",
    campaigns: "campaigns",
    primaryAction: "list",
  },
  onboardingSteps: {
    explore: "Exploring your properties...",
    understand: "Understanding your market...",
    insights: "Discovering local opportunities...",
    prepare: "Preparing your workspace...",
    generate: "Creating listing posts...",
  },
  businessDataLabels: {
    itemSingular: "Property",
    itemPlural: "Properties",
    launchLabel: "New Campaign",
    categoryLabel: "Property Type",
    collectionLabel: "Listing Collection",
    serviceLabel: "Service",
    offerLabel: "Promotion",
  },
  contentTypeLabels: [
    { key: "just_listed", label: "Just Listed" },
    { key: "market_insight", label: "Market Insight" },
    { key: "open_house", label: "Open House" },
  ],
  recommendationTemplates: [
    { type: "listing_post", tier: "core", title: "Post a New Listing", description: "Promote a property with key details to attract buyers.", priority: "high", guidance: "Create a 'just listed' post highlighting a property's best features. Include address, price, bedrooms, bathrooms, square footage, and unique selling points. Make it scroll-stopping.", conditions: { hasData: true } },
    { type: "open_house_post", tier: "core", title: "Promote an Open House", description: "Drive traffic to your upcoming open house event.", priority: "high", guidance: "Create an open house announcement post. Include the date, time, address, and a compelling reason to attend. Build excitement and urgency.", conditions: {} },
    { type: "price_drop_alert", tier: "core", title: "Announce a Price Reduction", description: "Re-engage interested buyers with a price drop alert.", priority: "high", guidance: "Create a price reduction alert post for a listing. Emphasize the new price, the value proposition, and create urgency to act now before it's gone.", conditions: { hasData: true } },
    { type: "client_testimonial", tier: "core", title: "Share a Client Success Story", description: "Build trust with a real testimonial or success story.", priority: "high", guidance: "Share a client success story — how the agent helped a buyer or seller achieve their goal. Use specific details and outcomes to build credibility.", conditions: { hasData: true } },
    { type: "market_update", tier: "secondary", title: "Share a Market Update", description: "Position yourself as a local market expert with fresh data.", priority: "medium", guidance: "Write a local market insight post sharing a surprising housing stat or trend. Be specific to the market area. Use real data if available.", conditions: {} },
    { type: "business_intro", tier: "secondary", title: "Introduce Your Services", description: "Tell your audience who you are and what you offer.", priority: "medium", guidance: "Write an introduction post for this real estate business. Highlight key services, years of experience, areas served, and what sets them apart from other agents.", conditions: { noPublished: true } },
    { type: "neighborhood_highlight", tier: "advanced", title: "Highlight a Neighborhood", description: "Showcase a local area to attract buyers to your market.", priority: "low", guidance: "Create a neighborhood highlight post. Feature local amenities, schools, dining, parks, and what makes the area special for homebuyers.", conditions: {} },
  ],
  ui: { icon: "Home" },
  techStack: [
    // ── Import Your Data ──
    {
      providerKey: "listing_feed",
      label: "Property Marketing",
      category: "data_source",
      priority: "core",
      status: "live",
      connectionMode: "manual",
      description: "Add properties manually or import from any source to power your marketing campaigns.",
      capabilities: ["imports", "content_source", "data_enrichment"],
      managedIn: "content_assets",
      manualSetup: {
        fields: [
          {
            key: "url",
            label: "Listing Website URL",
            type: "url",
            required: true,
            placeholder: "https://yourwebsite.com/listings",
          },
        ],
      },
    },
    {
      providerKey: "real_estate_crm",
      label: "Real Estate CRM",
      category: "crm",
      priority: "core",
      status: "live",
      connectionMode: "manual",
      description: "Import closed deals, client milestones, and testimonial signals to generate high-impact content.",
      capabilities: ["lead_sync", "client_sync", "content_source", "workflow_trigger"],
      manualSetup: {
        fields: [
          {
            key: "apiKey",
            label: "API Key",
            type: "password",
            required: true,
            placeholder: "Your Follow Up Boss API key",
          },
        ],
      },
    },
    {
      providerKey: "idx_website",
      label: "Website Content",
      category: "website",
      priority: "core",
      status: "live",
      connectionMode: "manual",
      description: "Use your website to teach the AI your brand voice, services, and local expertise.",
      capabilities: ["imports", "content_source", "lead_sync", "analytics_source"],
      manualSetup: {
        fields: [
          {
            key: "url",
            label: "Business Website URL",
            type: "url",
            required: true,
            placeholder: "https://yourrealtybrand.com",
          },
        ],
      },
    },
    {
      providerKey: "google_business_profile",
      label: "Google Business Profile",
      category: "data_enrichment",
      priority: "recommended",
      status: "live",
      connectionMode: "oauth",
      description: "Turn your Google reviews into social proof content and trust-building posts.",
      capabilities: ["testimonial_source", "content_source", "analytics_source"],
    },
    // ── Publish Your Content ──
    {
      providerKey: "facebook_page",
      label: "Facebook Page",
      category: "publishing",
      priority: "core",
      status: "live",
      connectionMode: "oauth",
      channelRef: "FACEBOOK",
      description: "Publish and schedule content to your Facebook business page.",
      capabilities: ["publishing", "analytics_source", "scheduling_target"],
    },
    {
      providerKey: "instagram_business",
      label: "Instagram Business",
      category: "publishing",
      priority: "core",
      status: "live",
      connectionMode: "oauth",
      channelRef: "INSTAGRAM",
      description: "Publish and schedule visual real estate content to Instagram.",
      capabilities: ["publishing", "analytics_source", "scheduling_target"],
    },
    // ── Enhance Your Workflow ──
    {
      providerKey: "transaction_management",
      label: "Transaction Management",
      category: "operations",
      priority: "recommended",
      status: "planned",
      connectionMode: "planned",
      description: "Use transaction milestones and workflow data to power smarter automation.",
      capabilities: ["document_source", "workflow_trigger", "client_sync"],
    },
    {
      providerKey: "esignature",
      label: "E-Signature",
      category: "documents",
      priority: "recommended",
      status: "planned",
      connectionMode: "planned",
      description: "Use signed document activity to support workflow automation.",
      capabilities: ["document_source", "workflow_trigger"],
    },
    {
      providerKey: "showing_scheduler",
      label: "Showing Scheduler",
      category: "operations",
      priority: "optional",
      status: "planned",
      connectionMode: "planned",
      description: "Use showing activity and appointments to support event-driven marketing.",
      capabilities: ["workflow_trigger", "client_sync"],
    },
    {
      providerKey: "open_house_lead_capture",
      label: "Open House Lead Capture",
      category: "operations",
      priority: "optional",
      status: "planned",
      connectionMode: "planned",
      description: "Capture and use open house visitor leads for follow-up and event-based campaigns.",
      capabilities: ["lead_sync", "workflow_trigger"],
    },
  ],
};
