// Ads-08 — LinkedIn launch sheet.
//
// Structured Markdown brief organized by Campaign → (Special Ad
// Category) → Destination → Audience → Budget → Creatives →
// Setup Checklist. Mirrors the Meta launch sheet shape (ads-07)
// for a consistent FE rendering and a consistent media-buyer
// experience across platforms.
//
// NOT a direct import. LinkedIn Campaign Manager's bulk-edit
// format is an account-specific Excel template; this brief is for
// human review + manual or paste-driven entry, not file upload.

import { formatMoney, slugifyForFilename } from "./_helpers.js";

// SquadAds objective → LinkedIn objective + confirm-note for
// ambiguous mappings. LinkedIn's objectives shift by account
// region; we pick the most common label and surface confirm-notes
// when the user must verify the exact wording inside Campaign
// Manager.
const OBJECTIVE_MAP = {
  AWARENESS: { linkedin: "Brand awareness", note: null },
  TRAFFIC: { linkedin: "Website visits", note: null },
  LEADS: {
    linkedin: "Lead generation",
    // Website Conversions is the alternative when the user has
    // the LinkedIn Insight Tag + a conversion event mapped.
    note: "LinkedIn: 'Lead generation' (default, uses LinkedIn's native lead form) or 'Website conversions' if your LinkedIn Insight Tag + conversion event are configured. Confirm in Campaign Manager.",
  },
  ENGAGEMENT: { linkedin: "Engagement", note: null },
  EVENT: {
    linkedin: "Event registrations",
    note: "LinkedIn: 'Event registrations' targets LinkedIn-native events; if your event is hosted off-platform, switch to 'Website visits' or 'Lead generation'. Confirm in Campaign Manager.",
  },
};

// LinkedIn ad-format hint per SquadAds channel + creative shape.
// Defaults to Single Image — by far the most common starting
// point; the user can switch to Video / Document / Carousel /
// Conversation Ad inside Campaign Manager based on creative.
function adFormatHint(channelHint, assetUrl) {
  if (channelHint === "LINKEDIN_ORGANIZATION_PAGE") return "Page-level (organic boost)";
  if (assetUrl && /\.(mp4|mov|webm)(\?|$)/i.test(assetUrl)) return "Video ad";
  if (assetUrl && /\.(pdf)(\?|$)/i.test(assetUrl)) return "Document ad";
  return "Single image ad";
}

function ctaHint(creativeCta, objective) {
  if (creativeCta && creativeCta.trim()) return creativeCta.trim();
  switch (objective) {
    case "LEADS":
      return "Sign Up";
    case "TRAFFIC":
      return "Learn More";
    case "AWARENESS":
      return "Learn More";
    case "ENGAGEMENT":
      return "Follow";
    case "EVENT":
      return "Register";
    default:
      return "Learn More";
  }
}

export const linkedinLaunchSheet = {
  format: "linkedin_launch_sheet",
  aliases: [],
  label: "LinkedIn Campaign Manager launch sheet",
  mimeType: "text/markdown; charset=utf-8",
  extension: "md",
  platform: "linkedin",
  isDirectImport: false,
  importStyle: "linkedin_launch_sheet",
  notes: [
    "Structured launch brief for LinkedIn Campaign Manager. LinkedIn's",
    "true bulk-edit format is an account-specific Excel template; this",
    "brief is for human review and manual or paste-driven setup, not a",
    "direct upload file. Setup checklist included.",
  ].join(" "),
  render(bundle, pkg) {
    const lines = [];
    const housing = bundle.package.specialCategory === "HOUSING";
    const objective = bundle.package.objective;
    const objMap = OBJECTIVE_MAP[objective] ?? { linkedin: objective, note: null };

    // ── Header ─────────────────────────────────────────────────
    lines.push(`# LinkedIn launch sheet — ${bundle.package.name}`);
    lines.push("");
    lines.push(`_Generated by Squadpitch · Package \`${pkg.id}\` · Exported ${bundle.exportedAt}_`);
    lines.push("");
    lines.push("> Squadpitch does not launch ads. This is a setup brief for");
    lines.push("> LinkedIn Campaign Manager — review, then create the campaign yourself.");
    lines.push("");

    // ── Special Ad Category ────────────────────────────────────
    // LinkedIn doesn't have a built-in "Special Ad Category" UI
    // like Meta, but Fair Housing Act compliance still applies to
    // housing ads regardless of platform. Surface the same
    // protected-class reminders.
    if (housing) {
      lines.push("## ⚠ Housing-restricted creative (Fair Housing Act)");
      lines.push("");
      lines.push("LinkedIn does not surface a 'Special Ad Category' control like Meta, but the **U.S. Fair Housing Act applies to housing ads on every platform**, including LinkedIn. Before publishing:");
      lines.push("");
      lines.push("- [ ] Do **not** use ZIP-only or narrow postal targeting.");
      lines.push("- [ ] Keep age targeting open (LinkedIn restricts age targeting for housing in supported regions; respect this even if the UI doesn't enforce it).");
      lines.push("- [ ] Do **not** narrow by gender, demographics, or job-seeker status that could imply protected-class targeting.");
      lines.push("- [ ] Review every variant's copy for protected-class language (familial status, age, religion, race, ethnicity, disability, national origin).");
      lines.push("");
      lines.push("Squadpitch's compliance gate already cleared demographic targeting and ran the protected-class copy linter, but LinkedIn's ad review + your own legal review remain authoritative.");
      lines.push("");
    } else if (bundle.package.specialCategory !== "NONE") {
      lines.push(`## ⚠ Special Ad Category: ${bundle.package.specialCategory}`);
      lines.push("");
      lines.push(`This package is tagged as ${bundle.package.specialCategory}. Review LinkedIn's restricted-ad policies for this category before publishing.`);
      lines.push("");
    }

    // ── Campaign ───────────────────────────────────────────────
    lines.push("## Campaign");
    lines.push("");
    lines.push(`- **Name:** ${bundle.package.name}`);
    lines.push(`- **Objective (LinkedIn):** ${objMap.linkedin}`);
    if (objMap.note) {
      lines.push(`  - _Note: ${objMap.note}_`);
    }
    lines.push(`  - _SquadAds objective hint: ${objective}_`);
    // Suggest an ad format. We pick by looking at the first variant's
    // asset since all variants normally share one format inside a
    // LinkedIn campaign.
    const firstAssetUrl = bundle.creatives[0]?.primaryAssetUrl ?? "";
    const firstChannel = bundle.creatives[0]?.channelHint ?? null;
    lines.push(`- **Suggested ad format:** ${adFormatHint(firstChannel, firstAssetUrl)} (switch to Video / Document / Carousel / Conversation Ad in Campaign Manager based on your creative)`);
    lines.push("");

    // ── Destination ────────────────────────────────────────────
    lines.push("## Destination");
    lines.push("");
    if (bundle.destination) {
      lines.push(`- **Kind:** ${bundle.destination.kind}`);
      if (bundle.destination.url) {
        lines.push(`- **URL:** <${bundle.destination.url}>`);
      } else if (bundle.destination.socialProfile) {
        lines.push(`- **Social profile:** ${bundle.destination.socialProfile}`);
      }
      if (bundle.destination.utm) {
        const utm = bundle.destination.utm;
        const utmPairs = Object.entries(utm)
          .filter(([, v]) => typeof v === "string" && v.trim())
          .map(([k, v]) => `\`utm_${k}=${v.trim()}\``);
        if (utmPairs.length > 0) {
          lines.push(`- **UTMs applied to URL:** ${utmPairs.join(", ")}`);
          lines.push("  - _LinkedIn does not auto-append UTMs; use the URL above verbatim._");
        }
      }
      if (Array.isArray(bundle.destination.pixelIds) && bundle.destination.pixelIds.length > 0) {
        lines.push(`- **LinkedIn Insight Tag partner ids:** ${bundle.destination.pixelIds.join(", ")}`);
      } else {
        lines.push("- **LinkedIn Insight Tag:** none configured in SquadAds — install the Insight Tag on the destination page if you want conversion tracking + retargeting audiences.");
      }
    } else {
      lines.push("_(no destination configured)_");
    }
    lines.push("");

    // ── Audience ───────────────────────────────────────────────
    lines.push("## Audience");
    lines.push("");
    const a = bundle.audience;
    if (a) {
      if (Array.isArray(a.locations) && a.locations.length > 0) {
        lines.push(`- **Locations:** ${a.locations.map((l) => `${l.value} (${l.kind})`).join(", ")}`);
      }
      if (Array.isArray(a.interests) && a.interests.length > 0) {
        lines.push(`- **Industries / interests:** ${a.interests.join(", ")}`);
      }
      if (Array.isArray(a.languages) && a.languages.length > 0) {
        lines.push(`- **Languages:** ${a.languages.join(", ")}`);
      }
      lines.push("- _LinkedIn's strongest filters are job title, seniority, company size, industry, and skills. Translate the interests above into LinkedIn-native filters inside Campaign Manager._");
      if (Array.isArray(a.customAudienceHints) && a.customAudienceHints.length > 0) {
        lines.push("- **Custom audience hints (Matched Audiences):**");
        for (const h of a.customAudienceHints) {
          lines.push(`  - ${h.kind}: ${h.description}`);
        }
      }
      if (a.housingRestricted) {
        lines.push("- ⚠ **Housing-restricted** — demographic targeting cleared by SquadAds; do not re-narrow inside LinkedIn.");
      }
    } else {
      lines.push("_(no audience configured)_");
    }
    lines.push("");

    // ── Budget ─────────────────────────────────────────────────
    lines.push("## Budget");
    lines.push("");
    const b = bundle.budget;
    if (b) {
      if (b.dailyBudgetCents != null) {
        lines.push(`- **Daily budget:** ${formatMoney(b.dailyBudgetCents, b.currency)}`);
      }
      if (b.totalBudgetCents != null) {
        lines.push(`- **Total budget:** ${formatMoney(b.totalBudgetCents, b.currency)}`);
      }
      if (b.currency) lines.push(`- **Currency:** ${b.currency}`);
      if (b.durationDays) lines.push(`- **Duration:** ${b.durationDays} days`);
      if (b.startsAt) lines.push(`- **Starts:** ${new Date(b.startsAt).toISOString().slice(0, 10)}`);
      if (b.endsAt) lines.push(`- **Ends:** ${new Date(b.endsAt).toISOString().slice(0, 10)}`);
      lines.push("- _LinkedIn's CPC + CPM are typically higher than Meta/TikTok. Plan for that when sizing the daily budget._");
    } else {
      lines.push("_(no budget configured)_");
    }
    lines.push("");

    // ── Creatives ──────────────────────────────────────────────
    lines.push(`## Creatives (${bundle.creatives.length} variant${bundle.creatives.length === 1 ? "" : "s"})`);
    for (const c of bundle.creatives) {
      lines.push("");
      lines.push(`### Variant ${c.variantIndex}${c.channelHint ? ` — ${c.channelHint}` : ""}`);
      lines.push("");
      lines.push(`- **Headline:** ${c.headline}`);
      lines.push("");
      lines.push(`- **Introductory text:**`);
      lines.push("");
      lines.push(c.primaryText.split("\n").map((l) => `  > ${l}`).join("\n"));
      lines.push("");
      if (c.description) {
        lines.push(`- **Description:** ${c.description}`);
      }
      lines.push(`- **CTA:** ${ctaHint(c.cta, objective)}`);
      if (c.primaryAssetUrl) {
        lines.push(`- **Primary asset:** <${c.primaryAssetUrl}>`);
      } else {
        lines.push("- **Primary asset:** _(none — upload the creative directly in Campaign Manager)_");
      }
      if (Array.isArray(c.additionalAssetUrls) && c.additionalAssetUrls.length > 0) {
        lines.push("- **Additional assets:**");
        for (const u of c.additionalAssetUrls) lines.push(`  - <${u}>`);
      }
      if (c.rationale) {
        lines.push(`- _Rationale: ${c.rationale}_`);
      }
    }
    lines.push("");

    // ── Setup checklist ────────────────────────────────────────
    lines.push("## SETUP CHECKLIST");
    lines.push("");
    lines.push("Work through these in LinkedIn Campaign Manager before submitting for review.");
    lines.push("");
    lines.push(`- [ ] Create a new campaign named **${bundle.package.name}**.`);
    lines.push(`- [ ] Set the **objective** to **${objMap.linkedin}** (confirm exact wording against your account's available objectives).`);
    lines.push(`- [ ] Pick the ad format that matches your creative (default suggestion: **${adFormatHint(firstChannel, firstAssetUrl)}**).`);
    if (housing) {
      lines.push("- [ ] Confirm targeting respects Fair Housing rules: no ZIP-only, no narrow age/gender/demographic filters.");
    }
    lines.push("- [ ] Configure audience using LinkedIn-native filters (job title, seniority, industry, etc.). Use the interests above as inspiration.");
    lines.push("- [ ] Install or verify the **LinkedIn Insight Tag** on the destination page if you want conversion tracking + retargeting.");
    lines.push("- [ ] For each Variant above, create one ad with the headline, introductory text, asset, CTA, and destination URL.");
    lines.push("- [ ] Confirm the **destination URL** (above) is correct and UTM tags are preserved.");
    lines.push("- [ ] Submit for LinkedIn ad review. Squadpitch did not launch this.");

    if (bundle.compliance.reviewNotes) {
      lines.push("");
      lines.push("## Internal review notes");
      lines.push("");
      lines.push(bundle.compliance.reviewNotes);
    }

    return {
      content: lines.join("\n"),
      filename: `${slugifyForFilename(pkg.name)}-${pkg.id.slice(-6)}.linkedin-launch-sheet.md`,
    };
  },
};
