// Ads-07 — Meta (Facebook + Instagram) launch sheet.
//
// Emits a structured Markdown brief organized by Campaign → Special
// Ad Category → Destination → Audience → Budget → Creatives →
// Setup Checklist. The format is intentionally human-readable —
// what you'd hand a media buyer or paste into a project doc, not
// a CSV import file.
//
// NOT a direct import. Meta Ads Manager does not accept arbitrary
// JSON/CSV imports; its bulk-edit format is account-specific. The
// descriptor sets `isDirectImport: false` and the FE renders this
// as "launch checklist / brief", not "one-click import".

import { formatMoney, slugifyForFilename } from "./_helpers.js";

// SquadAds objective → Meta objective + confirm-note for ambiguous
// mappings. Meta's exact objective wording shifts by account
// (Awareness/Reach, Sales/Conversions etc.); we pick a sensible
// default and surface confirm-notes when the user must verify.
const OBJECTIVE_MAP = {
  TRAFFIC: { meta: "Traffic", note: null },
  LEADS: {
    meta: "Leads",
    note: "Meta also exposes 'Sales' / 'Conversions' for lead-style funnels; confirm against your account's available objectives.",
  },
  AWARENESS: { meta: "Awareness", note: null },
  ENGAGEMENT: { meta: "Engagement", note: null },
  EVENT: {
    meta: "Engagement (Event responses)",
    note: "Meta surfaces event-response objectives under 'Engagement'; if you have an Event RSVP destination, confirm the right placement inside Ads Manager.",
  },
};

// Single-source-of-truth CTA hint per Meta convention. Meta CTAs
// are a fixed enum inside Ads Manager — we just nudge the user
// toward a sensible default if the SquadAds creative didn't set one.
function ctaHint(creativeCta, objective) {
  if (creativeCta && creativeCta.trim()) return creativeCta.trim();
  switch (objective) {
    case "LEADS":
      return "Sign Up";
    case "TRAFFIC":
      return "Learn More";
    case "AWARENESS":
      return "Learn More";
    case "ENGAGEMENT":
      return "Like Page";
    case "EVENT":
      return "Get Tickets";
    default:
      return "Learn More";
  }
}

export const metaLaunchSheet = {
  format: "meta_launch_sheet",
  aliases: [],
  label: "Meta / Facebook / Instagram launch sheet",
  mimeType: "text/markdown; charset=utf-8",
  extension: "md",
  platform: "meta",
  isDirectImport: false,
  importStyle: "meta_launch_sheet",
  notes: [
    "Structured launch brief for Meta Ads Manager (Facebook + Instagram).",
    "Open the file alongside Ads Manager and work through the setup",
    "checklist; this is not a bulk-import file — Meta's true bulk-edit",
    "format is account-specific.",
  ].join(" "),
  render(bundle, pkg) {
    const lines = [];
    const housing = bundle.package.specialCategory === "HOUSING";
    const objective = bundle.package.objective;
    const objMap = OBJECTIVE_MAP[objective] ?? { meta: objective, note: null };

    // ── Header ─────────────────────────────────────────────────
    lines.push(`# Meta launch sheet — ${bundle.package.name}`);
    lines.push("");
    lines.push(`_Generated by Squadpitch · Package \`${pkg.id}\` · Exported ${bundle.exportedAt}_`);
    lines.push("");
    lines.push("> Squadpitch does not launch ads. This is a setup brief for");
    lines.push("> Meta Ads Manager — review, then create the campaign yourself.");
    lines.push("");

    // ── Special Ad Category (prominent at top for HOUSING) ─────
    if (housing) {
      lines.push("## ⚠ Special Ad Category: HOUSING");
      lines.push("");
      lines.push("This package contains housing-related content. **Before publishing in Meta Ads Manager:**");
      lines.push("");
      lines.push("- [ ] Set Special Ad Category to **Housing** on the campaign.");
      lines.push("- [ ] Do **not** use ZIP-only targeting. Use city/region with ≥15-mile radius.");
      lines.push("- [ ] Do **not** narrow targeting by age (must stay 18–65) or by gender (must stay 'all').");
      lines.push("- [ ] Review every variant's copy for protected-class language (familial status, age, religion, race, ethnicity, disability, national origin).");
      lines.push("- [ ] Confirm the audience does **not** include narrow custom-audience hints.");
      lines.push("");
      lines.push("Squadpitch's compliance gate already cleared demographic targeting and ran the protected-class copy linter, but Meta's ad review is the final word.");
      lines.push("");
    } else if (bundle.package.specialCategory !== "NONE") {
      lines.push(`## ⚠ Special Ad Category: ${bundle.package.specialCategory}`);
      lines.push("");
      lines.push(`Before publishing, set the campaign's Special Ad Category to **${bundle.package.specialCategory}** inside Meta Ads Manager and review the platform's restricted-ad policies for this category.`);
      lines.push("");
    }

    // ── Campaign ───────────────────────────────────────────────
    lines.push("## Campaign");
    lines.push("");
    lines.push(`- **Name:** ${bundle.package.name}`);
    lines.push(`- **Objective (Meta):** ${objMap.meta}`);
    if (objMap.note) {
      lines.push(`  - _Note: ${objMap.note}_`);
    }
    lines.push(`  - _SquadAds objective hint: ${objective}_`);
    lines.push(`- **Special Ad Category:** ${bundle.package.specialCategory}`);
    lines.push("");

    // ── Destination ────────────────────────────────────────────
    lines.push("## Destination");
    lines.push("");
    if (bundle.destination) {
      lines.push(`- **Kind:** ${bundle.destination.kind}`);
      if (bundle.destination.url) {
        lines.push(`- **URL:** <${bundle.destination.url}>`);
      } else if (bundle.destination.socialProfile) {
        lines.push(`- **Social profile:** ${bundle.destination.socialProfile}`);
      }
      // UTMs — flagged because Meta does NOT auto-append; the user
      // needs to paste the URL with UTMs in Ads Manager.
      if (bundle.destination.utm) {
        const utm = bundle.destination.utm;
        const utmPairs = Object.entries(utm)
          .filter(([, v]) => typeof v === "string" && v.trim())
          .map(([k, v]) => `\`utm_${k}=${v.trim()}\``);
        if (utmPairs.length > 0) {
          lines.push(`- **UTMs applied to URL:** ${utmPairs.join(", ")}`);
          lines.push("  - _Meta does not auto-append UTMs; use the URL above verbatim._");
        }
      }
      if (Array.isArray(bundle.destination.pixelIds) && bundle.destination.pixelIds.length > 0) {
        lines.push(`- **Pixel IDs:** ${bundle.destination.pixelIds.join(", ")}`);
      } else {
        lines.push("- **Pixel:** none configured in SquadAds — add your Meta Pixel + conversion event mapping at the ad-set level if you want conversion tracking.");
      }
    } else {
      lines.push("_(no destination configured)_");
    }
    lines.push("");

    // ── Audience ───────────────────────────────────────────────
    lines.push("## Audience");
    lines.push("");
    const a = bundle.audience;
    if (a) {
      if (Array.isArray(a.locations) && a.locations.length > 0) {
        lines.push(`- **Locations:** ${a.locations.map((l) => `${l.value} (${l.kind})`).join(", ")}`);
      }
      if (a.ageMin || a.ageMax) {
        lines.push(`- **Age range:** ${a.ageMin ?? "—"} to ${a.ageMax ?? "—"}`);
      }
      lines.push(`- **Genders:** ${(a.genders ?? ["all"]).join(", ")}`);
      if (Array.isArray(a.interests) && a.interests.length > 0) {
        lines.push(`- **Interests:** ${a.interests.join(", ")}`);
      }
      if (Array.isArray(a.languages) && a.languages.length > 0) {
        lines.push(`- **Languages:** ${a.languages.join(", ")}`);
      }
      if (Array.isArray(a.customAudienceHints) && a.customAudienceHints.length > 0) {
        lines.push(`- **Custom audience hints:**`);
        for (const h of a.customAudienceHints) {
          lines.push(`  - ${h.kind}: ${h.description}`);
        }
      }
      if (a.housingRestricted) {
        lines.push("- ⚠ **Housing-restricted** — demographic targeting cleared by SquadAds; do not re-narrow inside Meta.");
      }
    } else {
      lines.push("_(no audience configured)_");
    }
    lines.push("");

    // ── Budget ─────────────────────────────────────────────────
    lines.push("## Budget");
    lines.push("");
    const b = bundle.budget;
    if (b) {
      if (b.dailyBudgetCents != null) {
        lines.push(`- **Daily budget:** ${formatMoney(b.dailyBudgetCents, b.currency)}`);
      }
      if (b.totalBudgetCents != null) {
        lines.push(`- **Total budget:** ${formatMoney(b.totalBudgetCents, b.currency)}`);
      }
      if (b.currency) lines.push(`- **Currency:** ${b.currency}`);
      if (b.durationDays) lines.push(`- **Duration:** ${b.durationDays} days`);
      if (b.startsAt) lines.push(`- **Starts:** ${new Date(b.startsAt).toISOString().slice(0, 10)}`);
      if (b.endsAt) lines.push(`- **Ends:** ${new Date(b.endsAt).toISOString().slice(0, 10)}`);
    } else {
      lines.push("_(no budget configured)_");
    }
    lines.push("");

    // ── Creatives ──────────────────────────────────────────────
    lines.push(`## Creatives (${bundle.creatives.length} variant${bundle.creatives.length === 1 ? "" : "s"})`);
    for (const c of bundle.creatives) {
      lines.push("");
      lines.push(`### Variant ${c.variantIndex}${c.channelHint ? ` — ${c.channelHint}` : ""}`);
      lines.push("");
      lines.push(`- **Headline:** ${c.headline}`);
      lines.push("");
      lines.push(`- **Primary text:**`);
      lines.push("");
      lines.push(c.primaryText.split("\n").map((l) => `  > ${l}`).join("\n"));
      lines.push("");
      if (c.description) {
        lines.push(`- **Description:** ${c.description}`);
      }
      lines.push(`- **CTA:** ${ctaHint(c.cta, objective)}`);
      if (c.primaryAssetUrl) {
        lines.push(`- **Primary asset:** <${c.primaryAssetUrl}>`);
      } else {
        lines.push("- **Primary asset:** _(none — upload the creative directly in Ads Manager)_");
      }
      if (Array.isArray(c.additionalAssetUrls) && c.additionalAssetUrls.length > 0) {
        lines.push("- **Additional assets:**");
        for (const u of c.additionalAssetUrls) lines.push(`  - <${u}>`);
      }
      if (c.rationale) {
        lines.push(`- _Rationale: ${c.rationale}_`);
      }
    }
    lines.push("");

    // ── Setup checklist ────────────────────────────────────────
    lines.push("## SETUP CHECKLIST");
    lines.push("");
    lines.push("Work through these in Meta Ads Manager before submitting for review.");
    lines.push("");
    lines.push(`- [ ] Create a new campaign named **${bundle.package.name}**.`);
    lines.push(`- [ ] Set the **objective** to **${objMap.meta}** (confirm exact wording against your account's available objectives).`);
    if (housing) {
      lines.push("- [ ] Set **Special Ad Category** to **Housing** — required before saving the campaign.");
    } else if (bundle.package.specialCategory !== "NONE") {
      lines.push(`- [ ] Set **Special Ad Category** to **${bundle.package.specialCategory}**.`);
    }
    lines.push("- [ ] Create one ad set with the audience + budget above. (Meta requires at least one ad set per campaign.)");
    lines.push("- [ ] For each Variant above, create one ad (copy, asset, CTA, destination URL) inside the ad set.");
    lines.push("- [ ] Apply your **Meta Pixel** + conversion event mapping at the ad-set level if you want conversion tracking.");
    lines.push("- [ ] Confirm the **destination URL** (above) is correct and the UTM tags are preserved.");
    if (housing) {
      lines.push("- [ ] Re-verify HOUSING-compliance copy + targeting before submitting.");
    }
    lines.push("- [ ] Submit for Meta ad review. Squadpitch did not launch this.");

    // ── Internal notes ─────────────────────────────────────────
    if (bundle.compliance.reviewNotes) {
      lines.push("");
      lines.push("## Internal review notes");
      lines.push("");
      lines.push(bundle.compliance.reviewNotes);
    }

    return {
      content: lines.join("\n"),
      filename: `${slugifyForFilename(pkg.name)}-${pkg.id.slice(-6)}.meta-launch-sheet.md`,
    };
  },
};
