// Ads-08 — Pinterest launch sheet.
//
// Structured Markdown brief organized the same way as Meta + LinkedIn
// for cross-platform consistency. Pinterest-specific guidance:
// asset URLs are reference only (Pinterest requires uploading the
// actual file to its asset library), Pin format hints, and Pinterest
// Tag (the equivalent of Meta Pixel / LinkedIn Insight Tag).
//
// NOT a direct import. Pinterest Ads Manager bulk-edit uses an
// account-specific Excel template; this brief is for setup +
// paste-driven entry, not file upload.

import { formatMoney, slugifyForFilename } from "./_helpers.js";

// SquadAds objective → Pinterest objective + confirm-note for
// ambiguous mappings. Pinterest's exact objective wording varies
// by account region; confirm-notes flag when the user must check.
const OBJECTIVE_MAP = {
  AWARENESS: { pinterest: "Brand awareness", note: null },
  TRAFFIC: { pinterest: "Consideration (Outbound clicks)", note: null },
  LEADS: {
    pinterest: "Conversions",
    note: "Pinterest: 'Conversions' is the lead-style default; some accounts also expose a 'Leads' objective. Confirm what's available inside Pinterest Ads Manager.",
  },
  ENGAGEMENT: { pinterest: "Engagement", note: null },
  EVENT: {
    pinterest: "Consideration (Outbound clicks)",
    note: "Pinterest: no native 'Event' objective — default is 'Consideration / Outbound clicks' driving to the event page; switch to 'Conversions' if you have RSVP-event tracking + Pinterest Tag configured.",
  },
};

// Pin format hint. Pinterest categorizes ads by Pin format (Standard,
// Video, Idea, Carousel, Collection). We default to Standard since
// most SquadAds creatives are a single image; the user can switch
// inside Pinterest Ads Manager based on the creative they upload.
function pinFormatHint(channelHint, assetUrl) {
  if (channelHint === "PINTEREST") return "Standard Pin (switch to Video Pin / Idea Pin / Carousel based on the asset you upload)";
  if (assetUrl && /\.(mp4|mov|webm)(\?|$)/i.test(assetUrl)) return "Video Pin";
  return "Standard Pin";
}

function ctaHint(creativeCta, _objective) {
  // Pinterest doesn't use Meta-style CTA chips on every ad format;
  // the closest convention is a Pin title + "Shop now" / "Learn
  // more" overlay on Catalog Sales / Conversions ads. Pass through
  // the SquadAds CTA if set; otherwise leave empty (the user
  // configures inside Pinterest based on Pin format).
  if (creativeCta && creativeCta.trim()) return creativeCta.trim();
  return "_(set by Pin format inside Pinterest Ads Manager)_";
}

export const pinterestLaunchSheet = {
  format: "pinterest_launch_sheet",
  aliases: [],
  label: "Pinterest Ads launch sheet",
  mimeType: "text/markdown; charset=utf-8",
  extension: "md",
  platform: "pinterest",
  isDirectImport: false,
  importStyle: "pinterest_launch_sheet",
  notes: [
    "Structured launch brief for Pinterest Ads Manager. Pinterest's true",
    "bulk-edit format is an account-specific Excel template; this brief",
    "is for setup + paste-driven entry. Image / video assets must be",
    "uploaded to Pinterest's asset library — URLs are reference only.",
  ].join(" "),
  render(bundle, pkg) {
    const lines = [];
    const housing = bundle.package.specialCategory === "HOUSING";
    const objective = bundle.package.objective;
    const objMap = OBJECTIVE_MAP[objective] ?? { pinterest: objective, note: null };

    // ── Header ─────────────────────────────────────────────────
    lines.push(`# Pinterest launch sheet — ${bundle.package.name}`);
    lines.push("");
    lines.push(`_Generated by Squadpitch · Package \`${pkg.id}\` · Exported ${bundle.exportedAt}_`);
    lines.push("");
    lines.push("> Squadpitch does not launch ads. This is a setup brief for");
    lines.push("> Pinterest Ads Manager — review, then create the campaign yourself.");
    lines.push("");

    // ── Special Ad Category ────────────────────────────────────
    // Pinterest doesn't expose Meta-style Special Ad Categories,
    // but the Fair Housing Act applies regardless of platform.
    if (housing) {
      lines.push("## ⚠ Housing-restricted creative (Fair Housing Act)");
      lines.push("");
      lines.push("Pinterest does not surface a 'Special Ad Category' control like Meta, but the **U.S. Fair Housing Act applies to housing ads on every platform**, including Pinterest. Before publishing:");
      lines.push("");
      lines.push("- [ ] Do **not** use ZIP-only or narrow postal targeting.");
      lines.push("- [ ] Keep age targeting open (do not narrow by age below 18 or above 65).");
      lines.push("- [ ] Do **not** narrow by gender or demographics that could imply protected-class targeting.");
      lines.push("- [ ] Review every Pin's copy for protected-class language (familial status, age, religion, race, ethnicity, disability, national origin).");
      lines.push("");
      lines.push("Squadpitch's compliance gate already cleared demographic targeting and ran the protected-class copy linter, but Pinterest's ad review + your own legal review remain authoritative.");
      lines.push("");
    } else if (bundle.package.specialCategory !== "NONE") {
      lines.push(`## ⚠ Special Ad Category: ${bundle.package.specialCategory}`);
      lines.push("");
      lines.push(`This package is tagged as ${bundle.package.specialCategory}. Review Pinterest's restricted-ad policies for this category before publishing.`);
      lines.push("");
    }

    // ── Campaign ───────────────────────────────────────────────
    lines.push("## Campaign");
    lines.push("");
    lines.push(`- **Name:** ${bundle.package.name}`);
    lines.push(`- **Objective (Pinterest):** ${objMap.pinterest}`);
    if (objMap.note) {
      lines.push(`  - _Note: ${objMap.note}_`);
    }
    lines.push(`  - _SquadAds objective hint: ${objective}_`);
    const firstAssetUrl = bundle.creatives[0]?.primaryAssetUrl ?? "";
    const firstChannel = bundle.creatives[0]?.channelHint ?? null;
    lines.push(`- **Suggested Pin format:** ${pinFormatHint(firstChannel, firstAssetUrl)}`);
    lines.push("");

    // ── Destination ────────────────────────────────────────────
    lines.push("## Destination");
    lines.push("");
    if (bundle.destination) {
      lines.push(`- **Kind:** ${bundle.destination.kind}`);
      if (bundle.destination.url) {
        lines.push(`- **URL:** <${bundle.destination.url}>`);
      } else if (bundle.destination.socialProfile) {
        lines.push(`- **Social profile:** ${bundle.destination.socialProfile}`);
      }
      if (bundle.destination.utm) {
        const utm = bundle.destination.utm;
        const utmPairs = Object.entries(utm)
          .filter(([, v]) => typeof v === "string" && v.trim())
          .map(([k, v]) => `\`utm_${k}=${v.trim()}\``);
        if (utmPairs.length > 0) {
          lines.push(`- **UTMs applied to URL:** ${utmPairs.join(", ")}`);
          lines.push("  - _Pinterest does not auto-append UTMs; use the URL above verbatim._");
        }
      }
      if (Array.isArray(bundle.destination.pixelIds) && bundle.destination.pixelIds.length > 0) {
        lines.push(`- **Pinterest Tag IDs:** ${bundle.destination.pixelIds.join(", ")}`);
      } else {
        lines.push("- **Pinterest Tag:** none configured in SquadAds — install the Pinterest Tag on the destination if you want conversion tracking + retargeting audiences.");
      }
    } else {
      lines.push("_(no destination configured)_");
    }
    lines.push("");

    // ── Audience ───────────────────────────────────────────────
    lines.push("## Audience");
    lines.push("");
    const a = bundle.audience;
    if (a) {
      if (Array.isArray(a.locations) && a.locations.length > 0) {
        lines.push(`- **Locations:** ${a.locations.map((l) => `${l.value} (${l.kind})`).join(", ")}`);
      }
      if (Array.isArray(a.interests) && a.interests.length > 0) {
        lines.push(`- **Interests / keywords:** ${a.interests.join(", ")}`);
      }
      if (Array.isArray(a.languages) && a.languages.length > 0) {
        lines.push(`- **Languages:** ${a.languages.join(", ")}`);
      }
      lines.push("- _Pinterest excels at interest-based + keyword targeting (Pinterest taxonomy + search keywords). Translate the SquadAds interests into Pinterest interest categories inside Ads Manager._");
      if (Array.isArray(a.customAudienceHints) && a.customAudienceHints.length > 0) {
        lines.push("- **Custom audience hints:**");
        for (const h of a.customAudienceHints) {
          lines.push(`  - ${h.kind}: ${h.description}`);
        }
      }
      if (a.housingRestricted) {
        lines.push("- ⚠ **Housing-restricted** — demographic targeting cleared by SquadAds; do not re-narrow inside Pinterest.");
      }
    } else {
      lines.push("_(no audience configured)_");
    }
    lines.push("");

    // ── Budget ─────────────────────────────────────────────────
    lines.push("## Budget");
    lines.push("");
    const b = bundle.budget;
    if (b) {
      if (b.dailyBudgetCents != null) {
        lines.push(`- **Daily budget:** ${formatMoney(b.dailyBudgetCents, b.currency)}`);
      }
      if (b.totalBudgetCents != null) {
        lines.push(`- **Total budget:** ${formatMoney(b.totalBudgetCents, b.currency)}`);
      }
      if (b.currency) lines.push(`- **Currency:** ${b.currency}`);
      if (b.durationDays) lines.push(`- **Duration:** ${b.durationDays} days`);
      if (b.startsAt) lines.push(`- **Starts:** ${new Date(b.startsAt).toISOString().slice(0, 10)}`);
      if (b.endsAt) lines.push(`- **Ends:** ${new Date(b.endsAt).toISOString().slice(0, 10)}`);
    } else {
      lines.push("_(no budget configured)_");
    }
    lines.push("");

    // ── Pins (creatives) ───────────────────────────────────────
    lines.push(`## Pins (${bundle.creatives.length} variant${bundle.creatives.length === 1 ? "" : "s"})`);
    lines.push("");
    lines.push("> **Important:** asset URLs below are reference only. Pinterest requires uploading the actual image/video files to your asset library inside Pinterest Ads Manager — link URLs are not accepted as the creative source.");
    for (const c of bundle.creatives) {
      lines.push("");
      lines.push(`### Pin ${c.variantIndex}${c.channelHint ? ` — ${c.channelHint}` : ""}`);
      lines.push("");
      lines.push(`- **Title (headline):** ${c.headline}`);
      lines.push("");
      lines.push(`- **Description (primary text):**`);
      lines.push("");
      lines.push(c.primaryText.split("\n").map((l) => `  > ${l}`).join("\n"));
      lines.push("");
      lines.push(`- **CTA:** ${ctaHint(c.cta, objective)}`);
      lines.push(`- **Pin format hint:** ${pinFormatHint(c.channelHint, c.primaryAssetUrl)}`);
      if (c.primaryAssetUrl) {
        lines.push(`- **Asset to upload (reference URL):** <${c.primaryAssetUrl}>`);
      } else {
        lines.push("- **Asset to upload:** _(none — choose the image/video for this Pin inside Pinterest Ads Manager)_");
      }
      if (Array.isArray(c.additionalAssetUrls) && c.additionalAssetUrls.length > 0) {
        lines.push("- **Additional assets (reference):**");
        for (const u of c.additionalAssetUrls) lines.push(`  - <${u}>`);
      }
      if (c.rationale) {
        lines.push(`- _Rationale: ${c.rationale}_`);
      }
    }
    lines.push("");

    // ── Setup checklist ────────────────────────────────────────
    lines.push("## SETUP CHECKLIST");
    lines.push("");
    lines.push("Work through these in Pinterest Ads Manager before submitting for review.");
    lines.push("");
    lines.push(`- [ ] Create a new campaign named **${bundle.package.name}**.`);
    lines.push(`- [ ] Set the **objective** to **${objMap.pinterest}** (confirm exact wording against your account's available objectives).`);
    lines.push(`- [ ] Pick the Pin format (default suggestion: **${pinFormatHint(firstChannel, firstAssetUrl)}**).`);
    if (housing) {
      lines.push("- [ ] Confirm targeting respects Fair Housing rules: no ZIP-only, no narrow age/gender/demographic filters.");
    }
    lines.push("- [ ] Configure audience using Pinterest interests + keywords. Use the SquadAds interests above as inspiration.");
    lines.push("- [ ] Install or verify the **Pinterest Tag** on the destination page if you want conversion tracking + retargeting.");
    lines.push("- [ ] For each Pin above, upload the actual image/video file to Pinterest's asset library and create one Pin (title, description, CTA, destination URL).");
    lines.push("- [ ] Confirm the **destination URL** (above) is correct and UTM tags are preserved.");
    lines.push("- [ ] Submit for Pinterest ad review. Squadpitch did not launch this.");

    if (bundle.compliance.reviewNotes) {
      lines.push("");
      lines.push("## Internal review notes");
      lines.push("");
      lines.push(bundle.compliance.reviewNotes);
    }

    return {
      content: lines.join("\n"),
      filename: `${slugifyForFilename(pkg.name)}-${pkg.id.slice(-6)}.pinterest-launch-sheet.md`,
    };
  },
};
