ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'REMIX_CONTENT';
ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'GENERATE_CAMPAIGN';
ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'REGENERATE_POST';
ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'EXTRACT_IMAGE';
