CREATE TYPE "OutreachStatus" AS ENUM ('DISCOVERED','QUALIFIED','PREVIEW_PENDING','PREVIEW_GENERATING','READY_TO_EMAIL','EMAIL_QUEUED','EMAIL_SENDING','EMAIL_SENT','CLAIMED','NO_EMAIL','INVALID_EMAIL','NO_ACTIVE_LISTINGS','DUPLICATE','SCRAPE_ERROR','UNSUPPORTED_PAGE','PREVIEW_FAILED','EMAIL_FAILED','BOUNCED','UNSUBSCRIBED','SUPPRESSED');
CREATE TYPE "OutreachRunStatus" AS ENUM ('RUNNING','PAUSED','STOPPED','COMPLETED','FAILED');
CREATE TYPE "SendingProvider" AS ENUM ('SMTP','GMAIL');

CREATE TABLE "agent_discovery_runs" ("id" TEXT PRIMARY KEY, "sourceUrl" TEXT NOT NULL, "sourceDomain" TEXT NOT NULL, "status" "OutreachRunStatus" NOT NULL DEFAULT 'RUNNING', "pagesScanned" INTEGER NOT NULL DEFAULT 0, "profilesFound" INTEGER NOT NULL DEFAULT 0, "qualifiedCount" INTEGER NOT NULL DEFAULT 0, "rejectedCount" INTEGER NOT NULL DEFAULT 0, "duplicateCount" INTEGER NOT NULL DEFAULT 0, "errorCount" INTEGER NOT NULL DEFAULT 0, "cursor" JSONB, "requestedBy" TEXT NOT NULL, "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "completedAt" TIMESTAMP(3));
CREATE TABLE "outreach_sending_accounts" ("id" TEXT PRIMARY KEY, "provider" "SendingProvider" NOT NULL, "displayName" TEXT NOT NULL, "fromEmail" TEXT NOT NULL, "replyTo" TEXT, "smtpHost" TEXT, "smtpPort" INTEGER, "smtpUsername" TEXT, "smtpPassword" TEXT, "smtpSecure" BOOLEAN NOT NULL DEFAULT true, "enabled" BOOLEAN NOT NULL DEFAULT true, "isDefault" BOOLEAN NOT NULL DEFAULT false, "hourlyLimit" INTEGER NOT NULL DEFAULT 25, "dailyLimit" INTEGER NOT NULL DEFAULT 100, "delaySeconds" INTEGER NOT NULL DEFAULT 60, "createdByAdminSub" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "agent_outreach_prospects" ("id" TEXT PRIMARY KEY, "discoveryRunId" TEXT, "prospectWorkspaceId" TEXT UNIQUE, "normalizedEmail" TEXT UNIQUE, "email" TEXT, "firstName" TEXT, "lastName" TEXT, "fullName" TEXT NOT NULL, "phone" TEXT, "brokerage" TEXT, "office" TEXT, "profileUrl" TEXT, "headshotUrl" TEXT, "sourceUrl" TEXT NOT NULL, "sourceDomain" TEXT NOT NULL, "stableIdentity" TEXT UNIQUE, "status" "OutreachStatus" NOT NULL DEFAULT 'DISCOVERED', "rejectionReason" TEXT, "listings" JSONB NOT NULL, "activeListingCount" INTEGER NOT NULL DEFAULT 0, "lastVerifiedAt" TIMESTAMP(3), "previewUrlEncrypted" TEXT, "claimUrlEncrypted" TEXT, "unsubscribeTokenHash" TEXT UNIQUE, "previewGeneratedAt" TIMESTAMP(3), "emailSubject" TEXT, "emailBody" TEXT, "sendingAccountId" TEXT, "emailProviderId" TEXT, "emailSentAt" TIMESTAMP(3), "claimedAt" TIMESTAMP(3), "lastError" TEXT, "discoveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "agent_outreach_events" ("id" TEXT PRIMARY KEY, "prospectId" TEXT NOT NULL, "type" TEXT NOT NULL, "message" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "outreach_suppressions" ("id" TEXT PRIMARY KEY, "normalizedEmail" TEXT NOT NULL UNIQUE, "reason" TEXT NOT NULL, "source" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "restoredAt" TIMESTAMP(3));

ALTER TABLE "agent_outreach_prospects" ADD CONSTRAINT "agent_outreach_prospects_discoveryRunId_fkey" FOREIGN KEY ("discoveryRunId") REFERENCES "agent_discovery_runs"("id") ON DELETE SET NULL;
ALTER TABLE "agent_outreach_prospects" ADD CONSTRAINT "agent_outreach_prospects_prospectWorkspaceId_fkey" FOREIGN KEY ("prospectWorkspaceId") REFERENCES "prospect_workspaces"("id") ON DELETE SET NULL;
ALTER TABLE "agent_outreach_prospects" ADD CONSTRAINT "agent_outreach_prospects_sendingAccountId_fkey" FOREIGN KEY ("sendingAccountId") REFERENCES "outreach_sending_accounts"("id") ON DELETE SET NULL;
ALTER TABLE "agent_outreach_events" ADD CONSTRAINT "agent_outreach_events_prospectId_fkey" FOREIGN KEY ("prospectId") REFERENCES "agent_outreach_prospects"("id") ON DELETE CASCADE;
CREATE INDEX "agent_discovery_runs_status_createdAt_idx" ON "agent_discovery_runs"("status", "createdAt");
CREATE INDEX "agent_outreach_prospects_status_discoveredAt_idx" ON "agent_outreach_prospects"("status", "discoveredAt");
CREATE INDEX "agent_outreach_prospects_sourceDomain_idx" ON "agent_outreach_prospects"("sourceDomain");
CREATE INDEX "agent_outreach_prospects_sendingAccountId_emailSentAt_idx" ON "agent_outreach_prospects"("sendingAccountId", "emailSentAt");
CREATE INDEX "agent_outreach_events_prospectId_createdAt_idx" ON "agent_outreach_events"("prospectId", "createdAt");
CREATE INDEX "outreach_sending_accounts_enabled_isDefault_idx" ON "outreach_sending_accounts"("enabled", "isDefault");
CREATE INDEX "outreach_suppressions_restoredAt_idx" ON "outreach_suppressions"("restoredAt");
